### ISSUE TITLE
[Question] Why are the extension methods on Timber's Tree object?

### ISSUE THREAD

**Issue by Plastix** [ajalt/timberkt#1]
I noticed that the extension methods in timberkt are on Timber's Tree class: `Timber.Tree.d(...)` Why is this the case? Why aren't they on the `Timber` class directly? Because of this I have to import your Timber object instead of using the regular Timber class. Thanks!

**Comment by NitroG42** [comment]
I think the answer is : In Kotlin, we can't add static extension for a class, so we can't add method for the original Timber class (using a lambda instead of a String).

**Comment by Plastix** [comment]
This makes a lot of sense. Thanks @NitroG42!
