### ISSUE TITLE
Provide a proxy to timber.log.Timber.DebugTree

### ISSUE THREAD

**Issue by JoshuaJamesOng** [ajalt/timberkt#5]
If  `com.github.ajalt.timberkt.Timber` is imported in the class you wish to plant the `Timber.DebugTree`, then you have to use a qualified import e.g. `Timber.plant(timber.log.Timber.DebugTree())`. 

It would be nice if `com.github.ajalt.timberkt.Timber` contained a function to return `timber.log.Timber.DebugTree` so that the code could read `Timber.plant(Timber.DebugTree())`.

**Comment by ajalt** [comment]
Good suggestion, thanks! I added a function `com.github.ajalt.timberkt.Timber.DebugTree()` that will return a new instance of the tree. It's in version 1.4.0.
